### PR TITLE
audit: error out with audit profile None

### PR DESCRIPTION
**Pull request by sttts**
Implementing https://github.com/openshift/enhancements/pull/792/files#diff-731ba465970a87a66f9744cfdd69a780f81235315e7ff6ea1232f7ef41ac7d7dR174.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by sttts** [comment]
How can this be tested? Is it automatically used in e2e-aws?

**Comment by sferich888** [comment]
/lgtm

As this is simply adding logs/warning to an script that is not run by default. 

> How can this be tested? Is it automatically used in e2e-aws?

We would need to put tests into the CI system (for this); This repo doesn't necessarily have a good way to test situations like this. cc: @deads2k

**Pull request merged**
