### PR TITLE
OCPBUGS-43058: [Backport 4.14] Multus is now a Pod and will be captured by normal

### PR DESCRIPTION
**Pull request by bpickard22**
oc adm must-gather command.

The multus.log file is removed since 4.16 and doesn't exist anymore.

original pr by @mkennell

Signed-off-by: Benjamin Pickard <bpickard@redhat.com>
(cherry picked from commit 121ea24190cb153f002cc239a098bf3d42a6e043)

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
/lgtm

**Comment by dougbtv** [comment]
/retitle OCPBUGS-43058: [Backport 4.14] Multus is now a Pod and will be captured by normal

**Pull request merged**
