### PR TITLE
gather_sriov: Fix typos and collect SRIOV cache at /var/lib/cni/sriov

### PR DESCRIPTION
**Pull request by andreaskaris**
gather_sriov: Fix typos and collect SRIOV cache at /var/lib/cni/sriov

### CODE REVIEW

**Comment by andreaskaris** [comment]
@zshi-redhat

**Comment by zeeke** [comment]
/lgtm

`/var/lib/cni/sriov` is very important to debug sriov-cni allocation issues

**Comment by andreaskaris** [comment]
@sferich888 @davemulford

**Pull request merged**
