### PR TITLE
OCPBUGS-42835: Removes reference to gather_multus_logs in 4.17

### PR DESCRIPTION
**Pull request by dougbtv**
This is an addendum to #445 -- which misses a fix Ben Pickard identified after its merge.

### CODE REVIEW

**Comment by dougbtv** [comment]
/retitle OCPBUGS-42835: Removes reference to gather_multus_logs in 4.17

**Comment by rbbratta** [comment]
needs approval.

**Comment by ingvagabund** [comment]
@sferich888 can you please approve? I am not in the list of approvers for 4.17.

**Comment by rbbratta** [comment]
@davemulford can you approve please?

**Pull request merged**
