### PR TITLE
CNF-9168: MetalLB: adjust to support frrk8s and small fix

### PR DESCRIPTION
**Pull request by fedepaol**
This PR adjusts the must gather collect script to reflect the latest metallb:

- it checks for the bgp backend and collect from the frr-k8s / speaker frr container according to the bgp backend
- it removes fetching the addresspool resource that was removed

Also, minor fix in fetching the pid from the right path.

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
Looks good.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
