### PR TITLE
Improve network data capture

### PR DESCRIPTION
**Pull request by pecameron**
Also, copy the must-gather.md from enhancements.
It was deleted. This is the version before the delete.

sdn-851 - Add network must-gather support to step-registry

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@rcarrillocruz @dcbw PTAL

**Comment by pecameron** [comment]
@RickJWagner @sferich888 PTAL

**Comment by pecameron** [comment]
@MaysaMacedo PTAL
maybe we should combine your PR 142 and this. What do you think?

**Comment by pecameron** [comment]
/retest
@dcbw PTAL

**Comment by dcbw** [comment]
@pecameron yeah I commented on #142 that I had a slight preference for getting that merged first and then rebasing yours on top, but no sense waiting too long if yours is ready to go.

**Comment by pecameron** [comment]
@dcbw @RickJWagner @sferich888 is there anything else that needs to be done before merging this? PTAL

**Comment by RickJWagner** [comment]
Hi @pecameron,
Thanks for your efforts here.  I've been out of the must-gather workspace for a while, so I dont feel qualified to be the sole reviewer.  I have read the changes and saw nothing to criticize, though.
Rick

**Comment by pecameron** [comment]
@RickJWagner Thanks for taking a look.

**Comment by pecameron** [comment]
@dcbw @sferich888 I did a rebase to resolve a conflict, so the lgtm was remove. Please take another look. is there anything else that needs to be done before merging this? PTAL

**Comment by sferich888** [comment]
/hold
/lgtm

I am putting a hold on this till @dcbw can review but it looks good from my perspective

**Comment by pecameron** [comment]
@dcbw Rich is holding pending your review PTAL

**Pull request merged**
