### PR TITLE
OCPBUGS-5195: fix audit gathering script

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by wangke19** [comment]
Pre-merge verified the PR, detail see [bug comments](https://issues.redhat.com/browse/OCPBUGS-5195?focusedCommentId=21791793&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21791793), works as expected.
/label qe-approved

**Comment by deads2k** [comment]
fixed in master in https://github.com/openshift/must-gather/pull/254.  overriding bug requirement

**Comment by deads2k** [comment]
@soltysh approved via slack, added label.

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Review by sanchezl — APPROVED** [review]
I would of preferred:
```
profile=$(oc get apiservers.v1.config.openshift.io cluster -o jsonpath=.spec.audit.profile)
```
but this will do.

**Pull request merged**
