### PR TITLE
Revert "NETOBSERV-987: Add must gather script for network observability"

### PR DESCRIPTION
**Pull request by sferich888**
Reverts openshift/must-gather#357

### CODE REVIEW

**Comment by sferich888** [comment]
@RickJWagner  / @davemulford  I think this was merged by accident; thus reverting.

**Review by RickJWagner — APPROVED** [review]
Quickly approving to get the revert in motion.

**Comment by sferich888** [comment]
@msherif1234 we may need help progressing this through tide (we seem to need a bugzilla/valid-bug label) do you know what tool / linkage is necessary here to make that happen?

**Comment by mschmitt25414** [comment]
@sferich888 'did you manage to define a valid bug for this?' - nope

**Comment by sferich888** [comment]
@mschmitt25414 No I was looking for th original filer to do so.

**Comment by msherif1234** [comment]
Did u try to use NETOBSERV-987 ?

**Comment by ingvagabund** [comment]
Closing in favor of https://github.com/openshift/must-gather/pull/390
/close

**Pull request closed without merging**
