### PR TITLE
network: actually call network gather script

### PR DESCRIPTION
**Pull request by dcbw**
Is this right?

@rcarrillocruz @danwinship @knobunc @wking

### CODE REVIEW

**Comment by danwinship** [comment]
I thought that the network log script was considered too heavyweight and so it was skipped by default but there was supposed to be some way to run it manually?

**Comment by wking** [comment]
> ... but there was supposed to be some way to run it manually?

With `oc adm must-gather gather_network_logs` or some such?

**Comment by dcbw** [comment]
@danwinship so how are we supposed to run it in CI? Just be on the ball and run it manually?

**Comment by danwinship** [comment]
I don't know. I just remember that `gather_network_logs` gets a bunch of logs on every node, and it was declared that we can't do that in every must-gather run, because in some clusters that would result in way too much data being generated.

**Pull request closed without merging**
