### PR TITLE
[release-4.8] Bug 2092264: Add networking resources

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of https://github.com/openshift/must-gather/pull/308

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by npinaeva** [comment]
Hey @kasturinarra, can you give me cherry-pick-approved label please?

**Pull request merged**
