### PR TITLE
Add csi-proxy logs collection in must-gather for Windows nodes

### PR DESCRIPTION
**Pull request by jrvaldes**
Follow-up to:

- https://github.com/openshift/windows-machine-config-operator/pull/1530

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Review by RickJWagner — COMMENTED** [review]
Looks good.

**Comment by jrvaldes** [comment]
> @RickJWagner: The label(s) `/label lgtm` cannot be applied. These labels are supported: `platform/aws, platform/azure, platform/baremetal, platform/google, platform/libvirt, platform/openstack, ga, tide/merge-method-merge, tide/merge-method-rebase, tide/merge-method-squash, px-approved, docs-approved, qe-approved, downstream-change-needed, rebase/manual, approved, backport-risk-assessed, bugzilla/valid-bug, cherry-pick-approved, jira/valid-bug, staff-eng-approved`. Is this label configured under `labels -> additional_labels` or `labels -> restricted_labels` in `plugin.yaml`?



@RickJWagner  Looks like the ci-bot was unhappy with the `/label lgtm` command. PTAL

**Review by RickJWagner — COMMENTED** [review]
This change looks ok.

**Pull request merged**
