### PR TITLE
RFE-5765: Collect etcd object count

### PR DESCRIPTION
**Pull request by oarribas**
Collects the etcd object count in the `etcd_info` directory as `json` file.

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
Looks good.

**Comment by oarribas** [comment]
Not sure why the `jira/valid-reference` label is missing, as the there is linked to RFE-5765. Maybe RFEs are not valid as jira links?

**Comment by oarribas** [comment]
@sferich888 , @RickJWagner , can you check the missing `jira/valid-reference` label?

**Comment by RickJWagner** [comment]
Hi @oarribas 
Thank you for this PR.  About the valid-reference label, could you please re-name this Issue Tracker so the RFE isn't contained in square brackets?  
I've been looking over other PRs, I didn't find any others that were referencing JIRAs in square brackets.  (There were some others that used the brackets, but these were used for release numbers.)
If that doesn't work, we can ask Ben Parees, I think he's done a lot of the work in https://raw.githubusercontent.com/openshift-eng/jira-lifecycle-plugin/refs/heads/main/cmd/jira-lifecycle-plugin/server.go.

Please give it a shot, see if it works.

**Pull request merged**
