### PR TITLE
OCPBUGS-43056: Open [Release-4.16] Multus is now a Pod and will be captured by normal

### PR DESCRIPTION
**Pull request by bpickard22**
oc adm must-gather command.

The multus.log file is removed since 4.16 and doesn't exist anymore.

original pr by @mkennell

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
/lgtm

**Comment by dougbtv** [comment]
/retitle OCPBUGS-43056: Open [Release-4.16] Multus is now a Pod and will be captured by normal

**Pull request merged**
