### PR TITLE
Bug 1715634: ensure we collect cluster version information

### PR DESCRIPTION
**Pull request by sferich888**
This should get cluster version information, with must-gather.

### CODE REVIEW

**Comment by sferich888** [comment]
/hold 
Putting a hold on this till https://github.com/openshift/must-gather/pull/95 merges.

**Comment by wking** [comment]
#95 has landed.  Leaving the hold until an architect green-lights for 4.1.z.

**Comment by sferich888** [comment]
@wking I pulled the "hold", it still needs an LGTM from someone but at this point, anyone can review and confirm (provide the lgtm).

**Comment by eparis** [comment]
This PR was reverted.
The bug was not approved for 4.1.1 and we have a very tight budget with QE about what bugs could be fixed.
The PR was unheld despite a senior member of OpenShift saying not to unhold.
The bots would not merge automatically (because it shouldn't have merged) and a human clicked merge anyway.

Please feel free to open another PR with this fix which may merge, via process, in a future 4.1.z.

I have, hopefully, removed access for people to click the green merge button.
We will be, hopefully soon, removing access for people to add or remove labels. You will need to use the bot command `/hold cancel` to remove labels in the future. (Though in this case, as trevor pointed out, you should not have done so without an architect's approval.)

**Pull request merged**
