### PR TITLE
Gather ostree related bits

### PR DESCRIPTION
**Pull request by cgwalters**
This has come up a lot, we should have had this from the start.

### CODE REVIEW

**Review by wking — APPROVED** [review]
[CI][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_must-gather/353/pull-ci-openshift-must-gather-master-e2e-aws/1636087205644472320/artifacts/e2e-aws/gather-must-gather/artifacts/must-gather.tar | tar tvz | grep 'rpm-ostreed\|ostree-finalize-staged'
-rw------- 1005240000/root    3726 2023-03-15 14:27 registry-build05-ci-openshift-org-ci-op-f8gcj91t-stable-sha256-875edd9f056b86f3227e63048ccd93ab4f615417e2df8d6081f542866a1e2a7a/host_service_logs/masters/ostree-finalize-staged_service.log
-rw------- 1005240000/root   35597 2023-03-15 14:27 registry-build05-ci-openshift-org-ci-op-f8gcj91t-stable-sha256-875edd9f056b86f3227e63048ccd93ab4f615417e2df8d6081f542866a1e2a7a/host_service_logs/masters/rpm-ostreed_service.log
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_must-gather/353/pull-ci-openshift-must-gather-master-e2e-aws/1636087205644472320/artifacts/e2e-aws/gather-must-gather/artifacts/must-gather.tar | tar xOz registry-build05-ci-openshift-org-ci-op-f8gcj91t-stable-sha256-875edd9f056b86f3227e63048ccd93ab4f615417e2df8d6081f542866a1e2a7a/host_service_logs/masters/ostree-finalize-staged_service.log
Mar 15 19:48:06.551534 ip-10-0-145-219 systemd[1]: Finished OSTree Finalize Staged Deployment.
Mar 15 19:48:09.481293 ip-10-0-145-219 systemd[1]: Stopping OSTree Finalize Staged Deployment...
Mar 15 19:48:09.545936 ip-10-0-145-219 ostree[2169]: Finalizing staged deployment
Mar 15 19:48:10.684602 ip-10-0-145-219 ostree[2169]: Copying /etc changes: 13 modified, 0 removed, 123 added
...
```

/lgtm

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_must-gather/353/pull-ci-openshift-must-gather-master-e2e-aws/1636087205644472320

**Comment by sferich888** [comment]
@cgwalters I don't have an issue with this; but do you understand that you will only get this from control plane nodes (by default). If your ok with that I can **/lgtm** this.

**Comment by cgwalters** [comment]
Ah, that does limit the utility a bit, but it's not fatal.

**Comment by sferich888** [comment]
Your call on how to proceed.

**Comment by cgwalters** [comment]
We should definitely get this in because often the fatal error will affect the control plane too.

**Review by sferich888 — APPROVED** [review]

**Pull request merged**
