### PR TITLE
CNV-23392: Bump base image to rehl 9

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Comment by ingvagabund** [comment]
https://github.com/openshift/release/tree/master/ci-operator/config/openshift/must-gather needs to be updated first.

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold 
We first need to land https://github.com/openshift/oc/pull/1652 to be able to move forward with this. Because just changing the builder isn't sufficient to move to rhel9

**Comment by ardaguclu** [comment]
https://github.com/openshift/must-gather/pull/421 will supersedes this PR

**Comment by sferich888** [comment]
[#421](https://github.com/openshift/must-gather/pull/421) merged so I believe this can be closed

/close

**Pull request closed without merging**
