### PR TITLE
Bug 1715634: ensure we collect cluster version information

### PR DESCRIPTION
**Pull request by sferich888**
@RickJWagner PTAL

### CODE REVIEW

**Comment by wking** [comment]
Can you drop a [`Bug 1715634:`][1] prefix on your subject?

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1715634

**Comment by sferich888** [comment]
We should block https://github.com/openshift/must-gather/pull/96 (until) this merges.

**Comment by wking** [comment]
Love it :heart: 

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/889/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/2148/artifacts/e2e-aws/must-gather/namespaces/openshift-cluster-version

**Comment by sferich888** [comment]
> Love it 
> 
> https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/889/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/2148/artifacts/e2e-aws/must-gather/namespaces/openshift-cluster-version

You also get - https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/889/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/2148/artifacts/e2e-aws/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions/version.yaml

**Comment by wking** [comment]
Wait, what?  We were already getting https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/500/artifacts/e2e-aws/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions.yaml

**Comment by sferich888** [comment]
> Wait, what? We were already getting https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/500/artifacts/e2e-aws/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions.yaml

Is that because this is merged?

**Comment by wking** [comment]
> Is that because this is merged?

No, [that run][1] is from May, well before this PR.  Checking [a recent run][2], I see both [`clusterversions.yaml`][3] and [`clusterversions/version.yaml`][4], while the May run had only the former.  So I'm not entirely clear on how these are being gathered or what changed when.  But it's fine; I'm happy they're getting collected ;).

[1]: https://prow.k8s.io/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/500
[2]: https://prow.k8s.io/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/721
[3]: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/721/artifacts/e2e-aws/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions.yaml
[4]: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/721/artifacts/e2e-aws/must-gather/cluster-scoped-resources/config.openshift.io/clusterversions/version.yaml

**Pull request merged**
