### PR TITLE
Bug 1726137: Fix BASE_COLLECTION_PATH on gather_network_logs

### PR DESCRIPTION
**Pull request by rcarrillocruz**
https://bugzilla.redhat.com/show_bug.cgi?id=1726137

### CODE REVIEW

**Comment by sferich888** [comment]
What BZ is this connected to? 
Will we need to backport this to 4.1? If so where is the PR (cherrypick/bz) to connect to this?

**Comment by rcarrillocruz** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1720833

And yes, we need to backport to 4.1. Without the fix, running the tool won't create the folder at root

**Comment by sferich888** [comment]
/retitle Bug 1726137: Fix BASE_COLLECTION_PATH on gather_network_logs

**Comment by sferich888** [comment]
/lgtm 

The cherry-pick PR can be linked to https://bugzilla.redhat.com/show_bug.cgi?id=1726144 (when that goes through).

**Comment by sferich888** [comment]
@mffiedler has QE had time to validate this? 
This validation seems to be holding up https://github.com/openshift/must-gather/pull/109 

cc: @jwforres

**Comment by mffiedler** [comment]
@sferich888 The 4.2 PR is not in a nightly build.  https://bugzilla.redhat.com/show_bug.cgi?id=1726137

**Pull request merged**
