### PR TITLE
NO-JIRA: Adding the missing clusterresourcequota and Flowcontrol resources

### PR DESCRIPTION
**Pull request by vlours**
PR following the RFE request #407 

Added the resources in the `group_resources` array.

### CODE REVIEW

**Comment by sferich888** [comment]
@soltysh who is the best person to review this?

**Comment by vlours** [comment]
@sferich888 
Thanks for checking on this one while I was away.

Do you think that I should create a Jira Ticket to draw attention on this PR?
Cheers,

**Comment by vlours** [comment]
@sferich888 @davemulford 
Any chance for this PR to be reviewed? And do I need to create a valid Jira request too, as part of the needs?
> Needs approved, jira/valid-reference, lgtm labels.

I did not created one, as the modification was just to add additional basic openshift components in the collection scripts.
Please let me know how to get this PR moving forward.
Thanks! 🙇

**Comment by sferich888** [comment]
@vlours I am going to give the a `lgtm` as I don't see why we can't include this. 

/lgtm

**Comment by sferich888** [comment]
/retitle NOJIRA: Adding the missing clusterresourcequota and Flowcontrol resources

**Comment by sferich888** [comment]
/retitle NO-JIRA: Adding the missing clusterresourcequota and Flowcontrol resources

**Pull request merged**
