### PR TITLE
Bug 1887446: [release-4.5]Backport `gather_core_dumps` 

### PR DESCRIPTION
**Pull request by astoycos**
Backport `gather_core_dump` Functionality to OCP 4.5 for CI Runs that use the functionality, and also bring in port and flow dumping in `gather_network_logs`

### CODE REVIEW

**Comment by davemulford** [comment]
@astoycos the changes look okay, but this needs a valid bug in order to be merged. Do you have one?

**Comment by astoycos** [comment]
@davemulford Sorry about that should be all set now :)

**Comment by davemulford** [comment]
No worries!

/lgtm

**Comment by davemulford** [comment]
@sdodson, if you agree with this change, can you please add the cherry-pick-approved label?

**Comment by sdodson** [comment]
> @sdodson, if you agree with this change, can you please add the cherry-pick-approved label?

patch manager is a rotation and they only accept changes when the window is open so they should get to this according to that schedule

**Pull request merged**
