### PR TITLE
Adding automated insights archive collection

### PR DESCRIPTION
**Pull request by sferich888**
This should resolve https://github.com/openshift/must-gather/issues/255

cc: @iNecas

### CODE REVIEW

**Comment by iNecas** [comment]
`/var/lib/insights-operator` keeps some history of archives in there: I guess we would be fine keeping just the last one of it, and perhaps considering unpacking it, so that it would be ready to be used once the must-gather is decompressed.

**Comment by sferich888** [comment]
@iNecas i guess I just need to know what the CCX team wants? To me it's odd to collect this when this is already streamed back to Red Hat.?.?

**Comment by iNecas** [comment]
The reasons:
1. facing reality, all in once is easier than combining the data at end-user level when troubleshooting
2. insights-operator might be disabled to send data, but it's still generating tarballs - allows having same structure of data even for disconnected clusters
3. despite must-gather collecting larger dataset, it's not collecting everything insights-operator does: this could reduce the efforts done on enhancing the data collection - we wouldn't have to update must-gather if insights-operator already collected the data (and the reasons lay in (1) or (2))
4. would make must-gather truly superset of what insights-operator gathers - would allow not having to have two separate conditions in insights rules

The reasons are mostly pragmatic. And given the IO payload is minimal compared to what must-gather has, I'm not seeing that much of downsides here. But if you feel strongly against this, I could live with that.

**Comment by sferich888** [comment]
I have no issues collecting the data; it just wasn't clear how it would be used. 

- Note: need to raise / discuss with @soltysh flags/options to 'oc rsync' that would let us do the filtering of files  (only get latest, etc) vs having to make this multiple calls with 'oc'.

**Review by RickJWagner — APPROVED** [review]
Looks good to me.  One item stands out, it's only a problem if it's unintended.  Please make sure the dash (-) is intended in BASE_COLLECTION_PATH.  
-/must-gather          (do we really want the leading dash?)

**Comment by sferich888** [comment]
@RickJWagner that is a bash syntax for defaults ':-' is the separation identifier.

**Pull request merged**
