### PR TITLE
SDN-5066,OCPBUGS-33959: Remove needless multus log collection

### PR DESCRIPTION
**Pull request by martinkennelly**
Multus is now a Pod and will be captured by normal oc adm must-gather command.

The multus.log file is removed since 4.14 and doesn't exist anymore.

Previous PR is hung: https://github.com/openshift/must-gather/pull/429
Please see this PR for lgtm from multus team.

/assign @sferich888

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
Agree this commit removes the unneeded multus log collection.  I assume we provide the container needed for must-gather elsewhere.
Looks good.

**Comment by martinkennelly** [comment]
@sferich888 PTAL

**Pull request merged**
