### PR TITLE
OCPBUGS-10957: avoid monitoring routes and TLS

### PR DESCRIPTION
**Pull request by jan--f**

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by zhouying7780** [comment]
@jan--f  Since we have remove the define for 'CA_BUNDLE', we also need to remove it from `cleanup()` , because when I tested I hit : /usr/bin/gather_monitoring: line 26: CA_BUNDLE: unbound variable

**Comment by jan--f** [comment]
> @jan--f Since we have remove the define for 'CA_BUNDLE', we also need to remove it from `cleanup()` , because when I tested I hit : /usr/bin/gather_monitoring: line 26: CA_BUNDLE: unbound variable

Fixed.

**Pull request merged**
