### PR TITLE
bug 1834836: gather_network_logs - capture sbdb and nbdb

### PR DESCRIPTION
**Pull request by pecameron**
This captures the ovn database files on each master node
It also includes the node name in the file name of the
log files.

Bug 1834836
https://bugzilla.redhat.com/show_bug.cgi?id=1834836

SDN-946 - gather_network_logs - also capture sbdb and nbdb
https://issues.redhat.com/browse/SDN-946

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
/assign @sferich888
@sferich888 @JacobTanenbaum @dcbw PTAL

**Comment by sferich888** [comment]
This looks fine to me. 

/lgtm
/hold

Adding a hold on this till someone from the Networking team does a review.

**Comment by pecameron** [comment]
@sferich888 This was reviewed by @JacobTanenbaum who added lgtm. Can the hold be cancelled?

**Comment by sferich888** [comment]
Yea no need to hold if what have approvals from the right teams.

**Comment by pecameron** [comment]
@sferich888 I added a bug, what do I need to do to get this to merge?

**Comment by deads2k** [comment]
/retitle bug 1834836: gather_network_logs - capture sbdb and nbdb

**Comment by deads2k** [comment]
/title bug 1834836: gather_network_logs - capture sbdb and nbdb

**Pull request merged**
