### PR TITLE
Add network logs gathering by default

### PR DESCRIPTION
**Pull request by npinaeva**
Remove "for every node" collection loops from gather_network_logs,
this information is supposed to be collected on a per-node basis
(e.g. using sosreport).
Remove duplicating with /namespaces logs collection.
Add cluster scale information (services, endpoints, pods amount).
Add gather_network_logs to default gather script.
Remove stale gather_network_ovn_trace script.

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

### CODE REVIEW

**Review by sferich888 — APPROVED** [review]
/lgtm
/hold 

As I want @davemulford and others to confirm this also looks good. We are dropping a lot from the collection.


@iNecas should the cc'd team review to make sure that insights rules using must gather aren't affected? Who is the best person to do that?

**Comment by iNecas** [comment]
@sferich888 I would say in these cases, the best is to file a ticket against INSIGHTOCP to let the rules team triage that.

**Comment by sferich888** [comment]
@npinaeva can you raise this ticket just to confirm/provide awareness to that team that this will land in the 4.10 timeframe.

**Comment by dulek** [comment]
@npinaeva: Looks good from Kuryr side, is there a PR adding `-d` to `ip l` in the scripts gathering info from network namespaces?

**Comment by npinaeva** [comment]
> @npinaeva can you raise this ticket just to confirm/provide awareness to that team that this will land in the 4.10 timeframe.

Shouldn't break anything, https://issues.redhat.com/browse/INSIGHTOCP-535

**Comment by npinaeva** [comment]
> @npinaeva: Looks good from Kuryr side, is there a PR adding `-d` to `ip l` in the scripts gathering info from network namespaces?

Not yet, but it should be added here https://github.com/sosreport/sos/blob/main/sos/report/plugins/networking.py#L207-L216

**Pull request merged**
