### PR TITLE
create a no-arg command for collecting information related to a control-plane

### PR DESCRIPTION
**Pull request by deads2k**
`openshift-must-gather inspect-control-plane`

@sferich888 @juanvallejo  as an example.

### CODE REVIEW

**Comment by soltysh** [comment]
> openshift-must-gather inspect-control-plane

I was wondering about it, I'd like to have a few flavors, but I'm not sure we should be writing command for each. So possible solutions might be:
1. `openshift-must-gather inspect <what>` and we'd have a series of sub-commands for every component.
2. `openshift-must-gather inspect --component <what>` and we'd have flag for every component. 
Wdyt?

**Comment by deads2k** [comment]
> 2\. `openshift-must-gather inspect --component <what>` and we'd have flag for every component.

Not this.  I think this command should stay neutral.  

Consider `oc gather-my-cluster` versus `oc gather this/resource`.  The former is strongly opinionated and will result in anger from people who want one thing more or one thing less or in this use-case do something different or handle 403s for these resources specially.  The latter is internally consistent about its behavior and surprisingly hard to have opinions about.  I think that `inspect` is the latter case


/hold

holding while we consider our options.

**Comment by deads2k** [comment]
This proved a possibility, but until we have a need, I think we'll go with a folder of bash scripts.

**Pull request closed without merging**
