### PR TITLE
Bug 2039382: Add +x permission to gather_metallb_logs

### PR DESCRIPTION
**Pull request by liornoy**
Execution permission was missing causing "Permission denied" error

### CODE REVIEW

**Comment by cgoncalves** [comment]
LGTM

**Comment by liornoy** [comment]
@sferich888 Please note that the script gather_insights is also without execution permissions. is it a bug? do you want me to file a fix for it as well?

**Review by RickJWagner — APPROVED** [review]
Strange looking PR. (The text reads 'Empty file', so I checked to be certain there really were some contents in /gather_metallb_logs.)  I see the icon indicating the change from 644->755, looks good.

**Comment by cgoncalves** [comment]
@sferich888 could you please help in reviewing and approving this PR? Thank you!

**Comment by cgoncalves** [comment]
Thanks, @sferich888!
It seems we still need the bugzilla/valid-bug label in order to complete all the checks and merge. Anything I can do to help (Lior is out of office)?

**Comment by cgoncalves** [comment]
/retitle Bug 2039382: Add +x permission to gather_metallb_logs

**Pull request merged**
