### PR TITLE
Collect etcd object count

### PR DESCRIPTION
**Pull request by kenneth-dsouza**
Etcd health/performance can often be degraded due high object count.  In this pull request, I am adding command to collect etcd object count.  This information will help support.

### CODE REVIEW

**Comment by sferich888** [comment]
@tjungblu do we want to collect etcd information this way or should we collect it via metrics? 
cc: @soltysh

**Review by RickJWagner — COMMENTED** [review]
Looks good.  Thanks for providing this information, which seems it will be useful to support.

**Review by soltysh — APPROVED** [review]
After discussion with etcd team, this is useful information
/approve

**Comment by soltysh** [comment]
/lgtm cancel
talking with Eric about potential options here
/hold

**Review by soltysh — CHANGES_REQUESTED** [review]
@kenneth-dsouza have a look at my comment in https://github.com/openshift/must-gather/pull/382#pullrequestreview-1649070628, where I argue about how to best address the data you're trying to add to must-gather here. Sync with the authors of that other PR, to help deliver the fix which will also address your use-case.

**Pull request closed without merging**
