### PR TITLE
collection-scripts/gather: Add imagecontentsourcepolicies.operator.openshift.io

### PR DESCRIPTION
**Pull request by wking**
Catching up with openshift/api@700fd891c4 (openshift/api#470).

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
MCO ecosystem acts on this object, so I think they should add it to the relatedObjects list and must-gather will get it.

**Comment by sferich888** [comment]
I agree. @wking can we close this in favor of related object in the mco?

**Comment by wking** [comment]
MCO `relatedObjects` handling is broken at the moment, but is also hard to fix.  I've filed [rhbz#1780362][1] for that, but can we get this as a temporary stopgap?

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1780362

**Comment by sferich888** [comment]
We need an issue/tracker to pull this out, when that BZ is resolved. 

/lgtm

**Comment by wking** [comment]
> We need an issue/tracker to pull this out, when that BZ is resolved.

[Filed][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1781435

**Pull request merged**
