### PR TITLE
OCPBUGS-24523: [release-4.12] Add csi-proxy logs collection in must-gather for Windows nodes

### PR DESCRIPTION
**Pull request by jrvaldes**
This is a manual cherry-pick of https://github.com/openshift/must-gather/pull/374

### CODE REVIEW

**Review by RickJWagner — COMMENTED** [review]
Looks good.

**Comment by jrvaldes** [comment]
@sferich888 could you help with `/label backport-risk-assessed` ?

cc @RickJWagner

**Comment by jrvaldes** [comment]
@sferich888  I think this PR falls under the [Backports Approvals in Repositories Where QE Does Not Verify Changes](https://docs.google.com/document/d/1PC87sSFa_zGCk95kXDW-wrVxnlgBmkHqpOgQnd4bbUw/edit#heading=h.fngsn7u47sga) category. 

Could you also help with `/label cherry-pick-approved` ?

cc @RickJWagner

**Comment by mtnbikenc** [comment]
@sferich888 @RickJWagner Following up on the request for `/label cherry-pick-approved`.  We'd like to get this bug closed out this sprint and only have a few days left.

**Comment by mtnbikenc** [comment]
Based on [this list](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/must-gather/_pluginconfig.yaml#L11-L18) the following users should be able to add the required cherry-pick-approved label.
@kasturinarra @lihongan @zhouying7780 @xingxingxia

Also, it appears the repo is configured to add the cherry-pick-approved label when the backport-risk-assessed label is applied, however that didn't happen.

Any help in untangling this situation is greatly appreciated.

**Comment by kasturinarra** [comment]
> Based on [this list](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/must-gather/_pluginconfig.yaml#L11-L18) the following users should be able to add the required cherry-pick-approved label. @kasturinarra @lihongan @zhouying7780 @xingxingxia
> 
> Also, it appears the repo is configured to add the cherry-pick-approved label when the backport-risk-assessed label is applied, however that didn't happen.
> 
> Any help in untangling this situation is greatly appreciated.

sorry about that, adding it now.

**Comment by kasturinarra** [comment]
> /label cherry-pick-approved

@rrasouli since this is a backport and if you are unable to set the cherry-pick-approved label please help check the file here https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/must-gather/_pluginconfig.yaml#L11-L18 (similar file is present for all openshift components, thanks !!) and do a @ on us so that we can add the same.

**Pull request merged**
